version: 2

updates:
  - assignees:
      - sk4la
    directory: /
    labels:
      - dependencies
    package-ecosystem: github-actions
    schedule:
      interval: daily
    target-branch: master
