name: dwarf2json

on:
  schedule:
    - cron: 0 2 * * 1,3,5
  push:
    branches:
      - master
    paths:
      - .github/workflows/dwarf2json.yml
      - src/dwarf2json/**
      - README.md

env:
  DOCKER_TAG_ALPINE: "3.15"
  DOCKER_TAG_DWARF2JSON: "0.6.0"
  GIT_TAG_DWARF2JSON: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --iso-8601 --utc )"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: docker/build-push-action@v2
        with:
          context: src/dwarf2json
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:${{ env.DOCKER_TAG_DWARF2JSON }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:latest
          build-args: |
            ALPINE_VERSION=${{ env.DOCKER_TAG_ALPINE }}
            GIT_TAG_DWARF2JSON=${{ env.GIT_TAG_DWARF2JSON }}
            PRODUCT_BUILD_COMMIT=${{ env.GITHUB_SHA }}
            PRODUCT_BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
          short-description: ${{ github.event.repository.description }}
