name: dwarf2json-edge

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - master
      - staging
    paths:
      - .github/workflows/dwarf2json.yml
      - src/dwarf2json/**
      - README.md

env:
  DOCKER_TAG_ALPINE: latest
  DOCKER_TAG_DWARF2JSON: edge
  GIT_TAG_DWARF2JSON: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601 --utc)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: docker/build-push-action@v6
        with:
          context: src/dwarf2json
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:${{ env.DOCKER_TAG_DWARF2JSON }}
          build-args: |
            DOCKER_TAG_ALPINE=${{ env.DOCKER_TAG_ALPINE }}
            GIT_TAG_DWARF2JSON=${{ env.GIT_TAG_DWARF2JSON }}
            PRODUCT_BUILD_COMMIT=${{ github.sha }}
            PRODUCT_BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
          short-description: ${{ github.event.repository.description }}
