name: Stable

on:
  push:
    branches:
      - master

env:
  DOCKER_TAG_ALPINE: "3.15"
  DOCKER_TAG_DWARF2JSON: "0.6.0"
  DOCKER_TAG_VOLATILITY3: "1.0.1"
  GIT_TAG_DWARF2JSON: master
  GIT_TAG_PYTHON_YARA: v4.1.3
  GIT_TAG_VOLATILITY3: v1.0.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --iso-8601 --utc )"

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: docker/build-push-action@v2
        with:
          context: src/dwarf2json
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:${{ env.DOCKER_TAG_DWARF2JSON }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json:latest
          build-args: |
            ALPINE_VERSION=${{ env.DOCKER_TAG_ALPINE }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            BUILD_COMMIT=${{ env.GITHUB_SHA }}
            GIT_TAG_DWARF2JSON=${{ env.GIT_TAG_DWARF2JSON }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/dwarf2json
          short-description: ${{ github.event.repository.description }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
        uses: docker/build-push-action@v2
        with:
          context: src/volatility3
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3:${{ env.DOCKER_TAG_VOLATILITY3 }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3:latest
          build-args: |
            ALPINE_VERSION=${{ env.DOCKER_TAG_ALPINE }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            BUILD_COMMIT=${{ env.GITHUB_SHA }}
            GIT_TAG_PYTHON_YARA=${{ env.GIT_TAG_PYTHON_YARA }}
            GIT_TAG_VOLATILITY3=${{ env.GIT_TAG_VOLATILITY3 }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
          short-description: ${{ github.event.repository.description }}
