name: volatility3

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 0
  push:
    branches:
      - development
      - master
      - staging
    paths:
      - .github/workflows/volatility3.yml
      - src/volatility3/**
      - README.md

env:
  DOCKER_TAG_ALPINE: latest
  DOCKER_TAG_VOLATILITY3: "2.7.0"
  # No tags/releases declared in the repository so we use the development branch.
  GIT_TAG_JPCERT_SYMBOLS: main
  GIT_TAG_PYTHON_YARA: v4.5.0
  GIT_TAG_VOLATILITY3: v2.7.0
  # No tags/releases declared in the repository so we use the development branch.
  GIT_TAG_VOLATILITY3_COMMUNITY: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601 --utc)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
        uses: docker/build-push-action@v6
        with:
          context: src/volatility3
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3:${{ env.DOCKER_TAG_VOLATILITY3 }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3:latest
          build-args: |
            DOCKER_TAG_ALPINE=${{ env.DOCKER_TAG_ALPINE }}
            GIT_TAG_JPCERT_SYMBOLS=${{ env.GIT_TAG_JPCERT_SYMBOLS }}
            GIT_TAG_PYTHON_YARA=${{ env.GIT_TAG_PYTHON_YARA }}
            GIT_TAG_VOLATILITY3=${{ env.GIT_TAG_VOLATILITY3 }}
            GIT_TAG_VOLATILITY3_COMMUNITY=${{ env.GIT_TAG_VOLATILITY3_COMMUNITY }}
            PRODUCT_BUILD_COMMIT=${{ github.sha }}
            PRODUCT_BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility3
          short-description: ${{ github.event.repository.description }}
