name: volatility-edge

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - master
      - staging
    paths:
      - .github/workflows/volatility.yml
      - src/volatility/**
      - README.md

env:
  # Stuck at this minor version since Alpine Linux no longer distributes Python 2 through its official repositories.
  DOCKER_TAG_ALPINE: "3.15"
  # No new tags/releases declared in the repository so we use the `edge` tag that follows the main development branch.
  DOCKER_TAG_VOLATILITY: edge
  GIT_TAG_PYTHON_YARA: v4.4.0
  # No new tags/releases declared in the repository so we use the development branch.
  GIT_TAG_VOLATILITY: master
  # No new tags/releases declared in the repository so we use the development branch.
  GIT_TAG_VOLATILITY_COMMUNITY: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601 --utc)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
        uses: docker/build-push-action@v5
        with:
          context: src/volatility
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:${{ env.DOCKER_TAG_VOLATILITY }}
          build-args: |
            DOCKER_TAG_ALPINE=${{ env.DOCKER_TAG_ALPINE }}
            GIT_TAG_PYTHON_YARA=${{ env.GIT_TAG_PYTHON_YARA }}
            GIT_TAG_VOLATILITY=${{ env.GIT_TAG_VOLATILITY }}
            GIT_TAG_VOLATILITY_COMMUNITY=${{ env.GIT_TAG_VOLATILITY_COMMUNITY }}
            PRODUCT_BUILD_COMMIT=${{ github.sha }}
            PRODUCT_BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
          short-description: ${{ github.event.repository.description }}
