name: volatility-stable

on:
  schedule:
    - cron: 0 2 * * 0
  push:
    branches:
      - master

env:
  DOCKER_TAG_ALPINE: "3.15"
  DOCKER_TAG_VOLATILITY: "2.6.1"
  GIT_TAG_PYTHON_YARA: v4.1.3
  GIT_TAG_VOLATILITY3: "2.6.1"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --iso-8601 --utc )"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
        uses: docker/build-push-action@v2
        with:
          context: src/volatility
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:${{ env.DOCKER_TAG_VOLATILITY3 }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:latest
          build-args: |
            ALPINE_VERSION=${{ env.DOCKER_TAG_ALPINE }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            BUILD_COMMIT=${{ env.GITHUB_SHA }}
            GIT_TAG_PYTHON_YARA=${{ env.GIT_TAG_PYTHON_YARA }}
            GIT_TAG_VOLATILITY=${{ env.GIT_TAG_VOLATILITY }}

      # - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
      #     short-description: ${{ github.event.repository.description }}
