name: volatility

on:
  push:
    branches:
      - development
      - master
      - staging
    paths:
      - .github/workflows/volatility.yml
      - src/volatility/**
      - README.md

env:
  # Stuck at this version since Alpine Linux no longer distributes Python 2 through its official
  # repositories.
  DOCKER_TAG_ALPINE: "3.15.4"
  DOCKER_TAG_VOLATILITY: "2.6.1"
  GIT_TAG_PYTHON_YARA: v4.2.3
  GIT_TAG_VOLATILITY: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Get current date
        id: date
        run: echo "date=$(date --iso-8601 --utc)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
        uses: docker/build-push-action@v3
        with:
          context: src/volatility
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:${{ env.DOCKER_TAG_VOLATILITY }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/volatility:latest
          build-args: |
            ALPINE_VERSION=${{ env.DOCKER_TAG_ALPINE }}
            GIT_TAG_PYTHON_YARA=${{ env.GIT_TAG_PYTHON_YARA }}
            GIT_TAG_VOLATILITY=${{ env.GIT_TAG_VOLATILITY }}
            PRODUCT_BUILD_COMMIT=${{ env.GITHUB_SHA }}
            PRODUCT_BUILD_DATE=${{ steps.date.outputs.date }}

      - name: Update Docker Hub repository description for ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}/volatility
          short-description: ${{ github.event.repository.description }}
